version: 2

project_name: downloaderbot

builds:
  - id: downloaderbot
    main: ./cmd/app
    binary: downloaderbot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commitHash={{ .ShortCommit }}

archives:
  - id: downloaderbot
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^Merge "

release:
  github:
    owner: sxwebdev
    name: downloaderbot
  footer: |
    **Full Changelog**: https://github.com/sxwebdev/downloaderbot/compare/{{ .PreviousTag }}...{{ .Tag }}
