log:
  format: json
  level: info
  console_colored: false
  trace: fatal
  with_caller: false
  with_stack_trace: false
ops:
  enabled: false
  network: tcp
  tracing_enabled: false
  metrics:
    enabled: false
    path: /metrics
    port: "10000"
    basic_auth:
      enabled: false
      username: ""
      password: ""
  healthy:
    enabled: false
    path: /healthy
    port: "10000"
    livenesspath: /livez
    readinesspath: /readyz
  profiler:
    enabled: false
    path: /debug/pprof
    port: "10000"
    write_timeout: 60
grpc:
  enabled: true
  addr: :9000
  network: tcp
  reflect_enabled: false
  health_check_enabled: false
  logger_enabled: false
  recovery_enabled: false
telegram_bot_api_token: ""
