services:
  downloaderbot:
    image: ghcr.io/sxwebdev/downloaderbot:latest
    container_name: downloaderbot
    command: ["start"]
    environment:
      - DOWNLOADERBOT_TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
    restart: on-failure
