version: "3.9"

networks:
  downloaderbot_net:
    driver: bridge
    name: downloaderbot_net

volumes:
  minio-data-1:
  minio-data-2:

services:
  # downloaderbot
  downloaderbot:
    image: ${DOCKER_REPO}
    networks:
      - downloaderbot_net
    ports:
      - 9085:9000
    depends_on:
      - redis
    environment:
      - ENV_CI=${ENV_CI}
      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - LIMITER_CACHE_PREFIX=${LIMITER_CACHE_PREFIX}
      - REDIS_ADDR=redis:6379
      - S3_ACCESS_ID=${S3_ACCESS_ID}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BASE_URL=${S3_BASE_URL}
      - S3_BUCKET_NAME=downloaderbot
    restart: on-failure

  # redis
  redis:
    image: "redis:latest"
    restart: on-failure
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - downloaderbot_net
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./config/redis/redis-data:/var/lib/redis
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
