// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/bot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get
type GetInstagramLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *GetInstagramLinkRequest) Reset() {
	*x = GetInstagramLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInstagramLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstagramLinkRequest) ProtoMessage() {}

func (x *GetInstagramLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstagramLinkRequest.ProtoReflect.Descriptor instead.
func (*GetInstagramLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_bot_proto_rawDescGZIP(), []int{0}
}

func (x *GetInstagramLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type GetInstagramLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *GetInstagramLinkResponse) Reset() {
	*x = GetInstagramLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInstagramLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstagramLinkResponse) ProtoMessage() {}

func (x *GetInstagramLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstagramLinkResponse.ProtoReflect.Descriptor instead.
func (*GetInstagramLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_bot_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstagramLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_proto_bot_proto protoreflect.FileDescriptor

var file_proto_bot_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x62, 0x6f, 0x74, 0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x2e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x32, 0x5f, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67,
	0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bot_proto_rawDescOnce sync.Once
	file_proto_bot_proto_rawDescData = file_proto_bot_proto_rawDesc
)

func file_proto_bot_proto_rawDescGZIP() []byte {
	file_proto_bot_proto_rawDescOnce.Do(func() {
		file_proto_bot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bot_proto_rawDescData)
	})
	return file_proto_bot_proto_rawDescData
}

var file_proto_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bot_proto_goTypes = []interface{}{
	(*GetInstagramLinkRequest)(nil),  // 0: bot.GetInstagramLinkRequest
	(*GetInstagramLinkResponse)(nil), // 1: bot.GetInstagramLinkResponse
}
var file_proto_bot_proto_depIdxs = []int32{
	0, // 0: bot.BotService.GetInstagramLink:input_type -> bot.GetInstagramLinkRequest
	1, // 1: bot.BotService.GetInstagramLink:output_type -> bot.GetInstagramLinkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bot_proto_init() }
func file_proto_bot_proto_init() {
	if File_proto_bot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInstagramLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInstagramLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bot_proto_goTypes,
		DependencyIndexes: file_proto_bot_proto_depIdxs,
		MessageInfos:      file_proto_bot_proto_msgTypes,
	}.Build()
	File_proto_bot_proto = out.File
	file_proto_bot_proto_rawDesc = nil
	file_proto_bot_proto_goTypes = nil
	file_proto_bot_proto_depIdxs = nil
}
